### ISSUE TITLE
under Android throws MXBean not found

### ISSUE THREAD

**Issue by kacperros** [EasyRules/easyrules#32]
I've been trying to use Easy Rules in my Android app. Version 2.2.0 causes a MXBean not found error to be thrown during compilation. I am using org.easyrules:easyrules-core:2.2.0 in my gradle build. As far as I can tell this is caused by BasicRule requiring mxbean, which is not defined in Android SDK.

I'll be looking for a workaround while developing the app.

**Comment by benas** [comment]
Hi,

Thank you for pointing out this issue. 

Easy Rules has been made android compatible since v1.3. Looks like this is a regression.

I'll fix it asap and keep you informed.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

Sorry for the late reply. I've removed JMX API imports from the core module. It  should be android compatible now. Could you please give it a try with version 2.3.0-SNAPSHOT and keep me informed if this is ok for you? Many thanks upfront.

Kind regards
Mahmoud

**Comment by benas** [comment]
FYI, I'm preparing to release version 2.3 with this fix. Thank you for reporting the issue.
