### ISSUE TITLE
Is it possible to skip a rule execution using the listener or some events in the RuleEngine?

### ISSUE THREAD

**Issue by siaspa** [EasyRules/easyrules#34]
Hi, 

I just read the documentation, but I haven't seen if the engine allows a rule to exclude some other rules from evaluation/execution or to insert/add some new rules during the execution.

Should it be resolved in a two pass firing? With a new RuleEngine() inside the execution of a Rule?

Thank you in advance,
David

**Comment by benas** [comment]
Hi,

> I haven't seen if the engine allows a rule to exclude some other rules from evaluation/execution

This is possible using the `skipOnFirstFailedRule` or `skipOnFirstAppliedRule` parameters. See [rules engine parameters](http://www.easyrules.org/user-guide/rules-engine.html) 

> or to insert/add some new rules during the execution.

This is unfortunately not possible. It is a [known limitation](https://speakerdeck.com/benas/easy-rules?slide=15) of Easy Rules.

> Should it be resolved in a two pass firing? With a new RuleEngine() inside the execution of a Rule?

Probably yes. But I won't do it, it would be complicated. I would not try to use a tool if it is not designed to solve my problem easily.

Kind regards
Mahmoud

**Comment by benas** [comment]
Hi,

I was thinking to add a method to the listener API to be able to implement your feature request.

```java
public interface RuleListener {

    Rule beforeEvaluate(Rule rule);

    void beforeExecute(Rule rule);

    void onSuccess(Rule rule);

    void onFailure(Rule rule, Exception exception);

}
```

The method `beforeEvaluate` can be used to:

* define if the rule should be evaluated or not. The implementation can return null if the rule should be skipped.
* modify the rule (based on some context) before being evaluated and executed

What do you think of the idea?
Would love to hear your thoughts

Kind regards
Mahmoud

**Comment by siaspa** [comment]
Hi,

First of all, thank you for your work.

It sounds good. I tried to use the engine to write some validation rules
I’ll try to explain my scenario with an example to understand if it fits my needs.

Suppose you have this model objects

Person
               name:  String
               dateOfBirth: Date
               address: Address


Address
               name:  String
               zip: String
               country: String


RULES: Every attribute is required


When I check a Person object, I will execute some rules:

PersonNameRule -> name required
PersonDateOfBirthRule -> date of birth required
PersonAddressRequiredRule -> address required
PersonAddressFieldsRule -> addressRuleEngine.execute()
               In its execution this executes the rule related to address fields
               AddressNameRule -> address name required
               AddressZipRule -> zip code required
               AddressCountryRule  -> country required


PersonRules {
               registerRule(new PersonNameRule())
               …
}

AddressRules {
               registerRule(new AddressNameRule())
               …
}


Now suppose that I have some validators

PersonValidator(person)
               private personRuleEngine

boolean validate(personRules) {
               buildRuleEngine()
setupContexts(personRules);
               personRuleEngine().fireRules();
}

setupContexts() {
               personNameRule.setContext(person)
               //….
               personAddressRequiredRule.setContext(person)
               personAddressFieldsRule.setContext(person.address)

}
}

AddressValidator(address)
               private addressRuleEngine

boolean validate(addressRules) {
               buildRuleEngine()
setupContexts(addressRules);
               addressRuleEngine().fireRules();
}

setupContexts() {
               addressNameRule.setContext(address)
               //….

}
}



class PersonAddressFieldsRule

               boolean evaluate() {
                              return person.address != null;
              }

               execute() {
                              new AddressValidator().validate(person.address)
               }
}


Now the “context object”. Every Rule class has a Context object (I’ve extended the BasicRule class for this)
for Person*Rule is a person
for Address*Rule is an address


But the context is the place in which I run the rules.

The context could add a listener that can use the beforeEvaluate to check if a Rule should be skipped for any reason. It can return null or change the Rule.
Unfortunately getListeners() is not exposed, so the decision has to be made before firing the rules and not inside a rule.

I’ve written a listener to intercept the onFailure() and notify all the errors to a ErrorHandler and it caused me some trouble (but this is out of subject)

With the new feature, in this example I could register another listener, a  “context based” rule listener that could exclude some rules from being executed.
It should work.

Regards,
David

**Comment by benas** [comment]
Hi David,

I'm really sorry for the late reply.

As requested, I've added the `beforeEvaluate` method in the `RuleListener` interface. You can give it a try with version 2.3.0-SNAPSHOT and tell me if this is ok for you?

Kind regards
Mahmoud

**Comment by siaspa** [comment]
Hi, and thank you for the snapshot. 

I wrote an example to test the behavior of checkRules() and listener.beforeEvaluate() event and yes, they help the client to interact with the rule engine. But there are some aspects of the implementation that I'd like to point out:

1) checkRules() calls eachRule.evaluate() without calling listener.beforeEvaluate(). As a client that has registered a listener, it seems to me that an event called beforeEvaluate() should be called before calling evaluate() (or evaluate(CHECKING_RULES|FIRING_RULES)). Otherwise it should change its name.

2) checkRules() calls eachRule.evaluate() without concerning the rule priority order. Is it an issue?

3) When used in fireRules(), the name beforeEvaluate() seems to be generic, but the real goal of the method is something more specific. It can be skipRule/ruleAction(rule).
RuleAction = class (
	private Action action -> SKIP/EXECUTE/SKIP_TO_RULE(?);
	private Rule ruleToSkip; //?
}

 if the user uses it to return null or the rule. 
 
But the result method is not a boolean, it's a Rule. Do you think that a client can completely change the rule reference?

Regards,
David

**Comment by benas** [comment]
Thank you for taking time to test and for your feedback!

> 1) checkRules() calls eachRule.evaluate() without calling listener.beforeEvaluate().

I've fixed that. Now listeners are invoked before checking rules

> 2) checkRules() calls eachRule.evaluate() without concerning the rule priority order. Is it an issue?

Yes, fixed. Now rules are checked taking into account their order

> 3) When used in fireRules(), the name beforeEvaluate() seems to be generic

Here is the sequence of triggering rules: evaluate -> execute -> success | failure
The listener API provides methods according to this sequence: beforeEvaluate, beforeExecute, onSuccess and onFailure. This choice has been made to make it easy to the user to know when each callback method will be called.

> But the result method is not a boolean, it's a Rule. Do you think that a client can completely change the rule reference?

The user can decide to replace a rule before evaluation. He can also modify the rule according to a given context. I was thinking of the [BeanPostProcessor``](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/config/BeanPostProcessor.html) from spring which allow to completely replace a bean in a similar way. But as you suggest, returning a boolean is safer. I've updated the API to return a boolean. If the method returns true, the rule will be evaluated, otherwise the rule will be skipped.

You can try these updates in the latest snapshot.
Looking forward for your feedback.

Kind regards
Mahmoud

**Comment by siaspa** [comment]
Hello Mahmoud, I succesfully tested the changes you made! 
Regarding the boolean return value, I just asked. But I agree, returning a boolean should be enough for the purpose of the method and it's easy to understand.

Should I close the issue?

Thank you!

David

**Comment by benas** [comment]
Hi David,

Great news! I'm glad the updates were useful.

I'm closing the issue. This will be included in the upcoming release.

Cheers
Mahmoud
