### ISSUE TITLE
Can we store rules in a property file or Database?

### ISSUE THREAD

**Issue by devender-yadav** [EasyRules/easyrules#35]
Hi,

I am new to rule engines. I found **easyrules** interesting. 

I checked docs and found 3 ways to define rules- 

1.  implements `Rule` interface

2. Extends `BasicRule` class

3. Annotations in POJO

Is there any way to store rules in a property file or Database?

**Comment by benas** [comment]
Hi,

Unfortunately not. This is a [known "limititation"](https://speakerdeck.com/benas/easy-rules?slide=15) of Easy Rules.

I would like to add support for this feature but I don't find a clean/consistent way to define persistent rules. How do you suggest to do that? For example with properties file?

Kind regards
Mahmoud

**Comment by tantou** [comment]
Two years have passed,Any solution for persistent rules ?

**Comment by benas** [comment]
@tantou @devender-yadav v3.1 added support expression language. This allows you to store/load rules from a persistent resource (file, db, etc). More details in the wiki here: https://github.com/j-easy/easy-rules/wiki/expression-language-support

**Comment by devender-yadav** [comment]
Thanks for the update @benas!
