### ISSUE TITLE
Check Rules feature

### ISSUE THREAD

**Issue by thecederick** [EasyRules/easyrules#40]
Hi guys,

I found yours project very interesting for me, but I have some suggestions for you.

1. Sometimes it may be useful to not fire rules, but only check them like:
`boolean allRulesApplicable = ruleEngine.checkRules();`
Or return some rules result which can contain simple map (String, Boolean), where key is a Rule name and values is a "evaluate" method result. "fireRules" should return `boolean` or rules status.

2. Also it may be useful in conjunction with feature above to have rules evaluator to be able check rules like: 
`(RuleA and RuleB) or RuleC`

3. Maybe it will be a good idea to separate execute method from Rule itself to give additional level of abstraction. For example, if I use a CompositeRule it is possible that I want to execute a single "Job" for all contained rules. It can possibly give more flexibility with features 1 and 2. 

P.S. It is possible that I understand project use cases wrong :)

Thanks in advance.

**Comment by benas** [comment]
Hi @thecederick 

Thank you for these suggestions!

> Sometimes it may be useful to not fire rules, but only check them

Good idea indeed. This will allow the user to do some kind of "simulation" before firing rules. I've added a method `checkRules` in version 2.3.0-SNAPSHOT. You can give it a try, [here](https://github.com/EasyRules/easyrules/blob/feature-40-check-rules/easyrules-core/src/test/java/org/easyrules/core/DefaultRulesEngineTest.java#L120) is an example.

> Also it may be useful in conjunction with feature above to have rules evaluator to be able check rules

You can already do this: `( ruleA.evaluate() && ruleB.evaluate() ) || ruleC.evaluate()` . Do you believe Easy Rules should provide a `RuleEvaluator` API?

> Maybe it will be a good idea to separate execute method from Rule itself to give additional level of abstraction.

That was the case in the early stages of the project. We've got a separate concepts for `Condition`, `Action` and `Rule`. But we have decided to make a rule encapsulate the BOM, conditions and actions together as a unit.. That's easier :wink: 

Kind regards
Mahmoud

**Comment by thecederick** [comment]
Hi,

Thanks for the quick response!

> Good idea indeed. This will allow the user to do some kind of "simulation" before firing rules. I've added a method checkRules in version 2.3.0-SNAPSHOT. You can give it a try, here is an example.

Looks pretty good for me)

> You can already do this: ( ruleA.evaluate() && ruleB.evaluate() ) || ruleC.evaluate() . Do you believe Easy Rules should provide a RuleEvaluator API?

It is not always possible do it like you described, for example `@Condition` annotation and you do it outside of `Engine`.

Thank you for your project, hope to use it soon!

**Comment by benas** [comment]
Hi,

I've merged in the master branch the addition of the `checkRules` method in the `RulesEngine` API. It will be released soon in the 2.3 version.

In regards to the `RulesEvaluator` API, I've created a separate issue ( #42 ) and I planned to add it to the library too. Keep tuned :smile: 

Kind regards
Mahmoud
