### ISSUE TITLE
Adding rules at Runtime

### ISSUE THREAD

**Issue by mmorelo** [EasyRules/easyrules#43]
Hi, 

If I understood correctly, it is only possible to modify certain rules at runtime (like the example on changing the adult age). But it is not possible to add new rules whithout recompiling, right?

In my case, I need to inject new rules (java files in this case) to clients without them recompiling java code. Any other solution you can think of?

Thanks

**Comment by benas** [comment]
Hi @mmorelo 

> But it is not possible to add new rules whithout recompiling, right?

Indeed, this is not possible

> In my case, I need to inject new rules (java files in this case) to clients without them recompiling java code. Any other solution you can think of?

Just to be sure I understand. The idea is to read java code from a file, compile it on the fly, create the Rule object and register it at runtime. Is this your plan?
