### ISSUE TITLE
When I throw exception I get java.lang.reflect.UndeclaredThrowableException rather than flow going to the onFailure block.

### ISSUE THREAD

**Issue by kartheekgp** [EasyRules/easyrules#48]
I am not sure how to make the control go the failure block. 

Also, I have been trying to use this in spring but Autowire does not seem to be working as I am calling the RulesLauncher without that... I will try again to use autowiring!!

**Comment by benas** [comment]
Hi,

Thank you for pointing out this issue. 
Could you please provide a code example so I can understand what's happening?

Many thanks upfront
Kind regards
Mahmoud

**Comment by benas** [comment]
Any code example so I can help?

Which version are you using?

**Comment by kartheekgp** [comment]
Hello banas, 
Sorry for not replying earlier. I apologize.

I did a workaround and made sure that if the rule is successful, then only it should execure, otherwise, simply exit.

Its working fine now. I had 2 rules, if one fails it will go to other one.... If it succeeds it will not fo to the next one.

Also, how do yo call the following method?
 public void onFailure(org.easyrules.api.Rule rule, Exception exception) {
	}

I want to log if a rule has failed. How do you do that?

Regards,
Kartheek

**Comment by benas** [comment]
Hi, 

> how do yo call the following method?
public void onFailure(org.easyrules.api.Rule rule, Exception exception) {
}

You need to implement the `RuleListener` interface and register your implementation. See documentation here: http://www.easyrules.org/user-guide/rule-listener.html

Cheers
Mahmoud

**Comment by benas** [comment]
@kartheekgp Please close this issue if your problem is solved

**Comment by kartheekgp** [comment]
Thank you Benas.
