### ISSUE TITLE
Is a manner to integrate the fluent-validator with EasyRules ?

### ISSUE THREAD

**Issue by mamghari** [EasyRules/easyrules#53]
Hi,

It's not a real issue but a question if it is possible to integrate something developed in the fluent validator project. To be able to chain the validations, etc.
https://github.com/neoremind/fluent-validator

Thank you very much.

**Comment by benas** [comment]
Hi,

Thank you for the link to fluent validator, was not aware of this project.

> question if it is possible to integrate something developed in the fluent validator project. To be able to chain the validations, etc.

I'm not sure, but probably try to create a rule for each validation rule and then register rules in Easy rules and fire them? the engine will call fluent validator behind the scene.

Kind regards
Mahmoud

**Comment by benas** [comment]
@mamghari 

Have you been able to integrate easy rules with fluent validator?

**Comment by benas** [comment]
I assume this issue can be closed.
