### ISSUE TITLE
Multiple conditions for Rule execution

### ISSUE THREAD

**Issue by killoctal** [EasyRules/easyrules#54]
Hi,

I am really interested by using EasyRules, nice lib :-)

It would be helpful to be able to use several separated conditions for executing a Rule **at runtime**. Sometimes the same Rules should be used but at different conditions, depending on which scenario is used.

My idea is to create an interface with a single method (this way Java 1.8 users like me can use lambdas) and an aggregated `BasicRule`, here is a suggestion (not tested) :

Note: I called it `Evaluable` in this example for avoid potential conflict with annotation homonym.

```
public interface Evaluable {
    boolean evaluate();
}

public interface Rule extends Evaluable {
    // This is original interface, just evaluate() has been moved
}


public class MulticonditionalRule extends BasicRule {
    protected Set<Evaluable> conditions = new TreeSet<>();

    @Override
    public boolean evaluate() {
        if (conditions.isEmpty()) {
            return false;
        }
        for (Evaluable condition : conditions) {
            if (!condition.evaluate()) {
                return false;
            }
        }
        return true;
    }

    public MulticonditionalRule addCondition(Evaluable condition) {
        conditions.add(condition);
        return this; // chain
    }

    public void removeCondition(Evaluable condition) {
        conditions.remove(condition);
    }
}
```

Example of usage :

```
MulticonditionalRule rule = new MulticonditionalRule() {
    public void execute() {
        something();
    }
};

rule
    .addCondition( () -> blabla.isEnabled() )
    .addCondition( () -> something.isAccessible() )
    .addCondition( () -> otherThing.isRegistered() );

// "Combitional" usage of conditions, this is the point
if (bibiFeatureDisponible()) {
    rule.addCondition( () -> bibi.hasThing() );
}

// And for Java 1.6
rule.addCondition(new Evaluable() {
    @Override
    public boolean evaluate() {
        return foo.enabled();
    }
}
```

Best regards !
Gabriel

**Comment by benas** [comment]
Hi,

> I am really interested by using EasyRules, nice lib :-)

Thank you!

> It would be helpful to be able to use several separated conditions for executing a Rule at runtime. Sometimes the same Rules should be used but at different conditions, depending on which scenario is used.
> 
> My idea is to create an interface with a single method (this way Java 1.8 users like me can use lambdas) and an aggregated BasicRule, here is a suggestion (not tested) :

I think we can do that without making the `Rule` interface extend `Evaluable`.
Your example should work without having `public interface Rule extends Evaluable {..}` . Do you agree?
Using composition over inheritance as you did, which is a great example. We can even do it for actions too.

Kind regards
Mahmoud

**Comment by killoctal** [comment]
> Your example should work without having public interface Rule extends Evaluable {..} . Do you agree?
You are totally right, it was for keep  clean hierarchy :)

**Comment by toudidel** [comment]
I thought of multiple conditions and I don't see any reason for it. What's the difference between many conditions and one condition consists many subcondition. E.g.: condition1 && condition2 && condition3.

Advantage od chaining conditions into one bigger is that you may choose proper operator "and" or "or" (&& or ||).

**Comment by killoctal** [comment]
> Advantage of chaining conditions into one bigger is that you may choose proper operator

You are right, this is an advantage but the goal was to be able to simply define the condition at runtime.

Anyway I made a few tests and unfortunately the lib is not adapted to what I want to do (what I need is an inference engine), so I began to write mine. It will be Open Source too :-)

Best regards

**Comment by benas** [comment]
> Anyway I made a few tests and unfortunately the lib is not adapted to what I want to do (what I need is an inference engine)

Indeed, Easy Rules is not an inference engine.

> so I began to write mine. It will be Open Source too :-)

Cool! Don't hesitate to share it when published, I'm curious :smile:

**Comment by benas** [comment]
> what I need is an inference engine

Hey @killoctal , v3.1 adds a new [inference engine](https://github.com/j-easy/easy-rules/blob/master/easy-rules-core/src/main/java/org/jeasy/rules/core/InferenceRulesEngine.java#L33). See an example [here](https://github.com/j-easy/easy-rules/tree/master/easy-rules-tutorials/src/main/java/org/jeasy/rules/tutorials/airco). Is this what you are looking for?

v3.1 is not released yet, but you can give it a try using the snapshot version.

**Comment by killoctal** [comment]
Hi !
Glad to see this feature in your project :)
Finally I simply used *ListenableFuture *in my project, it did make the job.
Have a nice day
Gabriel



2017-12-14 13:40 GMT+01:00 Mahmoud Ben Hassine <notifications@github.com>:
