### ISSUE TITLE
Separating data from rule

### ISSUE THREAD

**Issue by nimitshah** [EasyRules/easyrules#56]
Hi,

I am really interested in using this library.
I think it would be good to separate the data on which rule execute. I mean if we can pass the data to rule when we fire the rule engine i.e. fireRules(data) which subsequently calls execute(data) on each rule. 

This will allow composition of rule engine separately from the data it needs at runtime.

If it's OK I can make a branch make the appropriate changes.

Thanks
Nimit Shah

**Comment by benas** [comment]
Hi,

Thank you. This is planned for next major version. See #36 and #37 

There is a nice [fork](https://github.com/augusto/MintRules) that introduces the concept of session, which is probably what you are looking for.

Also, I suggest you to read [this interesting thread](https://github.com/EasyRules/easyrules/issues/23) about rules contexts.

[All of these points](https://github.com/EasyRules/easyrules/milestone/4) are planned for the next major version.

Kind regards
Mahmoud

**Comment by nimitshah** [comment]
Thanks, I was looking for something sort of MintRules where runtime data can be passed when we fire the rules.

**Comment by benas** [comment]
Hi @nimitshah 

version 3 adds support for working memory to separate data from rules.

You can check an examples in #37 

Don't hesitate to give your feedback!

Kr
Mahmoud
