### ISSUE TITLE
Rule-Priority (Problem with sort sequence by overwriting the getPriority()-method)

### ISSUE THREAD

**Issue by JurMarky** [EasyRules/easyrules#57]
Hi,
you wrote in your documentation:

> If you decided to extend the BasicRule class, you can specify rule priority at construction time **or by overriding the getPriority() method**

Setting the priority via constructor achieves a correct order of my rules.  great!
if I extend from BasicRule.class and overwrite the getPriority()-method only and using the default-constructor fo the concrete class, in case of sorting the value that is returned by this method is always compared against DEFAULT_RULE_PRIORITY-value. So the order doesn't depend on the specified priority. 
I think the **problem** is the **compareTo-implementation** in the BasicRule.class

maybe
`if (priority < rule.getPriority()) { ` 
should better be
`if (getPriority() < rule.getPriority()) { ` 

`} else if (priority > rule.getPriority()) {`
should better be  
`} else if (getPriority() > rule.getPriority()) {`

for me extending the BasicRule.class with the current implementation and overwriting the getPriority()-method in the concrete class doesn't achieve a correct sort sequence?!

**Comment by benas** [comment]
Hi, thank you for reporting this issue.
Yes, this is probably a bug in Easy Rules.

I think your suggestion to use `getPriority()` method would work.
Can you open a PR with the corresponding test?

Many thanks upfront!
Kind regards
Mahmoud
