### ISSUE TITLE
EasyRules with Guice

### ISSUE THREAD

**Issue by sheldon-sminq** [EasyRules/easyrules#61]
We just started experimenting with EasyRules, our application uses Guice for DI.
On app launch we create a singleton instance of RulesEngine and register all rules (singletons) with the engine.

Each rule requires some data which in turn decides if some action needs to be done, this data keeps changing. So I have added a 

```
    public void setRuleData(Object data) {
        data = (Object) data;
    }
```
Before firing the rules we update the data as mentioned in 

```
        Rule currentRule = rules.get(ruleName);
        currentRule.setRuleData(data);
        rulesEngine.fireRules();
``` 

We are facing a problem where the rule data is overwritten by the next web service call, This happens in our integration tests when we test our api asynchronously.

Is there a way to prevent this? Is this related to #56?

**Comment by benas** [comment]
Hi,

I'm sorry for the late reply.

Probably related to issue 56. Will look into this asap.

Kind regards
Mahmoud

**Comment by sheldon-sminq** [comment]
For now i am creating a rules engine per thread.

**Comment by benas** [comment]
Hi,

I don't know if you've already seen [question 6 of the FAQ](http://www.easyrules.org/get-involved/faq.html#6). Since the rules engine is stateful (its state is the set of registered rules) and rules are also stateful (their state is the data they operate on), they are not thread safe.

> For now i am creating a rules engine per thread.

This is the way to go as suggested in the faq.

> We just started experimenting with EasyRules

What do you think about it? I would love to hear your feedback!

Kind regards
Mahmoud

**Comment by sheldon-sminq** [comment]
We wanted something light and this fit our needs, our rules are not very complex and other rule engines seem too complex for the task at hand.

We currently have it running in our dev environments, and plan to push it to production soon.

**Comment by benas** [comment]
Glad to hear that. If you have any question, I would love to help.

**Comment by benas** [comment]
Hi @sheldon-sminq 

V3 has been published with a new working memory abstraction. This makes the rules and the rules engine stateless. Your integration with Guice should be easier now and you should have no issue with your use case.

You can see an example of the new API in issue #37 
Don't hesitate to give your feedback!

Kind regards
