### ISSUE TITLE
Rule unregistration could be based on rule name

### ISSUE THREAD

**Issue by khandelwalankit** [EasyRules/easyrules#64]
In current version of easy rules, the unregister function in RulesEngine class requires parameter to be a instance of rule. 
But to unregister any existing rule (that is already registered), we don't necessarily require Rule object but just rule name which is registered with rule.name()
 
DefaultRulesEngine class has implementation: 
@Override
    public void unregisterRule(final Object rule) {
        rules.remove(asRule(rule));
    }

This could be helpful in easy and light weight unregistration of rules from rules engine at run time through any user defined admin tool without worrying about Rule Object. Let me know what you think about it.

**Comment by benas** [comment]
Hi,

Indeed, we should be able to unregister a rule by it's name. After all, rules have unique names within a rules engine, so it should be possible to do it. I'll check that and come back to you asap.

Thank you for this suggestion!

Kr
Mahmoud

**Comment by khandelwalankit** [comment]
Mahmoud, 
Thank you for your response. Let me know if i can be of any help in here. I would be glad to contribute.

**Comment by benas** [comment]
Hi,

Sure, you are welcome! I appreciate your help. Please don't hesitate to contribute to the project.

You can add the method to unregister a rule by name (hope there will be no clash with the current one)

Many thanks upfront.

Kind regards
Mahmoud

**Comment by khandelwalankit** [comment]
Sure. I will check on that and get back.
Thanks,
Ankit Khandelwal

**Comment by khandelwalankit** [comment]
This is code i am adding in DefaultRulesEngine class. Let me know if it makes sense :
```
public void unregisterRuleByName(final String ruleName){
        Rule rule = findRuleByName(ruleName);
        if(rule != null)
            unregisterRule(rule);
    }
```

    public Rule findRuleByName(String ruleName){
        for(Rule rule : rules){
            if(rule.getName().equalsIgnoreCase(ruleName))
                return rule;
        }
        return null;
    }

**Comment by benas** [comment]
Hi @khandelwalankit 

This is great! Thank you very much.

I've merged your PR and added you to the contributors list.

Just a small note, I'll rename the new method to `unregisterRule(String ruleName)`.

You can try your addition in v2.5.0-SNAPSHOT.

Kr
Mahmoud

**Comment by khandelwalankit** [comment]
Thanks! Yes that can be overloaded. I will check new version.
