### ISSUE TITLE
RulesEngine

### ISSUE THREAD

**Issue by OlegJava** [EasyRules/easyrules#67]
RulesEngine has fireRules() method. Is there a way to fire individual rule like fireRule(rulename)? I probably could just registerRule before calling fireRules and unregisterRule after execution, but I'd prefer to keep all rules registered and fire as needed.

**Comment by benas** [comment]
> Is there a way to fire individual rule like fireRule(rulename)

No, not yet. You can indeed register only one rule and fire it.

In next major version, we will have a RuleSet API in which you can register only one rule and then fire the rule set. Something like:

```java
RuleSet ruleSet = new RuleSet();
ruleSet.register(new MyRule());

RulesEngine rulesEngine = new InferenceRulesEngine(); // there will be multiple implementation (inference, backward chaining, rete, etc).

rulesEngine.fire(ruleSet);
```

**Comment by OlegJava** [comment]
Thanks, can you tell when the v3 is expected?

**Comment by benas** [comment]
Unfortunately no, but I'm planning to start working on v3 in the next few weeks.

I will let you know when the first snapshot is deployed in order to give it a try if you want.

Kind regards

**Comment by OlegJava** [comment]
Great, appreciate it!

**Comment by benas** [comment]
Hi @OlegJava 

I'm closing this issue for now, stay tuned for v3 !

Kr
Mahmoud
