### ISSUE TITLE
When you serve spring annotated rules behind a proxy like CGLIB

### ISSUE THREAD

**Issue by cgonul** [EasyRules/easyrules#71]
Hi guys;

First of all thanks for the great library. We are serving our spring beans behind CGLIB proxy by enabling the configuration   

`@EnableAspectJAutoProxy (proxyTargetClass = true)`

I think lots of people tend to do this. When we enable this configuration, the proxy classes become subclass of the target class and the annotations are not preserving. So the class @RuleDefinitionValidator tends to throw exceptions like

> Rule is not annotated with...  

These two links may highlight the situation:
http://stackoverflow.com/questions/1706751/retain-annotations-on-cglib-proxies
http://stackoverflow.com/questions/8974475/method-annotations-null-when-proxying-via-cglib

In my current environment I manage to work with CGLIB proxied @SpringRule annotations by changing the Easy Rule annotations like this 
```
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Rule {
```
I add the Inherited keyword.

And for working with methods I used spring AnnotationUtils class like 
 
```
AnnotationUtils.getAnnotation(annotatedType,targetAnnotation)
..
if (AnnotationUtils.findAnnotation(method,annotation) != null) {
```

If it sounds ok I would like the work on a pull request for easy rules supporting CGLIB proxied spring rules.

If it is not a good idea, I will continue on my local fork.

I have prepared a very rough commit 7aa26c303f28a957894354e59021eab944d40d91

Thanks again for the great library.

**Comment by benas** [comment]
Hi, 

Thank you, I see. You can add the `@ Inherited` if it does not introduce any regression. You are welcome to open a PR and I'll include it in the upcoming release.

In regards to `AnnotationUtils`, I prefer keeping the current implementation for now as I want easy rules to have no dependencies to spring-core.

Thank you.

Kr
Mahmoud

**Comment by benas** [comment]
Hi @cgonul 

I've added `@Inherited` annotation to `@SpringRule` in version 5.1.0-SNAPSHOT.

Can you give it a try and tell me if this is ok for you?

Kr
Mahmoud

**Comment by benas** [comment]
To use a snapshot version, please add sonatype's repo as described [here](https://github.com/EasyRules/easyrules#current-version)

**Comment by cgonul** [comment]
Hello benas;

Yes your modifications is working till some point. Sadly all of the other annotations and the methods for checking the annotions should be modified if we want easy rules work behind a proxy like cglib. However I started to think that it is a very specific request and I suspect that it may not be that common. Anyways less talk and more code. 

I have prepared an integration test just for checking if easy rules can work behind a proxy. You can checkout my branch from here : https://github.com/cgonul/easyrules/tree/integration_test_for_proxying

My new branch is up to date with your latest changes.

Here is the codes for integration tests : dffdf6b3d68d578d9d35b11530c6b71dcaadc6bc

In here all of my beans is served behind a proxy with the help of AspectConfiguration. When this happens the classes annotated with @SpringRule becomes the child class of the non proxied original classes. You can comment out the @Configuration annotation in AspectConfiguration class to disable the proxy. 

You will see that the integration test is not succeded. It fails with the following argument exception.

> Rule 'org.easyrules.spring.boot.integration.DummyRule$$EnhancerBySpringCGLIB$$7d00def8' must have a public method annotated with 'org.easyrules.annotation.Condition'

Which is triggered from RuleDefinitionValidator since easy rules can not find the Condition annotation on the DummyRule class, since the DummyRule is created as a child class of the original DummyRule by the Cglib proxy. 

This weekend I will work with this integration test and make easy rules works behind a proxy. The challange for me is that you do not like AnnotionUtils from spring core dependency. I will try to localize it. 

Thanks for your efforts.

**Comment by benas** [comment]
Hi,

Thank you for taking time to test!

> adly all of the other annotations and the methods for checking the annotations should be modified if we want easy rules work behind a proxy like cglib

Yes, this is what I say here:

https://github.com/EasyRules/easyrules/issues/66#issuecomment-288010301

This issue is related to #66 . Just adding `@Inherited` annotation is not enough.

> This weekend I will work with this integration test and make easy rules works behind a proxy

Great! But I suggest you to postpone this work for v3. The API will change so probably it is better to base your work on the new upcoming version. I'll let you know when the first snapshot will be deployed so you can have an idea about changes.

Probably we can close this issue in which we added the `@Inherited` annotation and can open a new one when v3 is out to make ER work behind a proxy ? What do you think?

BTW, I'm not sure spring support will be continued starting from v3..

Best regards
Mahmoud

**Comment by cgonul** [comment]
Ok. I understand that spring adds lots of complexity. 

> BTW, I'm not sure spring support will be continued starting from v3..
This just makes me somehow sad :)

We can always inject our spring beans from the constructor but lots of people like to use @Autowired annotation. Anyways if it adds lots of complexity then it makes sense. You are the owner. 

I will use EasyRules even if it has no spring support. 

Regards.

**Comment by benas** [comment]
Spring support will be easier in v3. Rules and the rules engine will be stateless so there will be no added value of the `RulesEngineFactoryBean`. Spring users will be able to create a rules engine instance without the need to this factory bean. Hence the deprecation.

I will provide a tutorial on this and I'll let you know about the first deploy of v3 snapshot.

I'm closing this issue for now.
