### ISSUE TITLE
Extend the listener to receive events when a rule evaluates to false

### ISSUE THREAD

**Issue by pklovesbacon** [EasyRules/easyrules#72]
I would like to be notified via the listener interface when a rule evaluates to false.  Thanks

**Comment by yisraelU** [comment]
I'd also like to request this feature

**Comment by benas** [comment]
Hi,

Good Idea! Thank you for this suggestion.

I've added a method `void afterEvaluate(Rule rule, boolean evaluationResult)` in the `RuleListener` API to get notified with the evaluation result of each rule.

This method will be invoked in both cases, so you can just grab the result you need to get notified on. You can already give a try with version 2.5.0-SNAPSHOT.

Looking forward for your feedback.

Kr
Mahmoud

**Comment by yisraelU** [comment]
where do i find 2.5.0 ?

**Comment by benas** [comment]
v2.5.0 is not released yet.

You can try the new feature with version 2.5.0-SNAPSHOT that can be found in sonatype's repository. See [here](https://github.com/EasyRules/easyrules#current-version)

**Comment by yisraelU** [comment]
would it be bad practice to use the listener to provide actions for the false side to the rule?

**Comment by benas** [comment]
Not a bad practice but it's not how it is designed to be used.

Easy rules is a production system (no else statement), so I guess you can create a rule for "else" and you are done.

Did you manage to use the snapshot version and test the new listener method?

**Comment by yisraelU** [comment]
Yes I have .
So far it's working great no troubles

**Comment by benas** [comment]
@pklovesbacon Have you got a chance to test the feature you requested?

**Comment by pklovesbacon** [comment]
Hi Benas,  Thanks for responding to this request. I really appreciate you adding this feature.
I'm currently tied up on another project but should be able to get back you on this in a few days time.

**Comment by pklovesbacon** [comment]
I got a chance to run it up in my test environment this morning.
Yes, it suits my need perfectly.
Thanks again , Paul.

**Comment by benas** [comment]
Great! Thank you for your time.

I'll include the fix in the upcoming release, keep tuned.
