### ISSUE TITLE
Are there rule tree samples for EasyRules?

### ISSUE THREAD

**Issue by just4look** [EasyRules/easyrules#73]
Are there rule tree samples for EasyRules?

Thanks.

**Comment by benas** [comment]
Hi,

Could you please elaborate on what a rule tree is?

**Comment by just4look** [comment]
An example of rule trees is a decision tree, for example https://en.wikipedia.org/wiki/Decision_tree
All actions are taken on leaves. You may also have a rule tree which the action is on root.

**Comment by benas** [comment]
Ah ok, a decision tree. There is no such an example for now but it would be a very good use case for easy rules!

Do you want to contribute such an example (even a hello world)? You are welcome if you want.

Kr
Mahmoud

**Comment by just4look** [comment]
Sure, if I decide to adopt it.
