### ISSUE TITLE
Deprecate Spring support

### ISSUE THREAD

**Issue by benas** [EasyRules/easyrules#74]
Spring support will be discontinued starting from v3.

The integration with spring caused a lot of confusions due to design issues in Easy Rules v2, mainly the rules and the engine being stateful. This issue will be addressed in v3.

Starting from v3, the rules engine will be stateless and the `RuleEngineFactoryBean` will have no added value. Hence the deprecation.

**Comment by zhao-staff-officer** [comment]
nice
